# Generated by Django 5.1.6 on 2025-12-17 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("row", "Row"),
                            ("column", "Column"),
                            ("container", "Container"),
                            ("section", "Section"),
                            ("card", "Card"),
                            ("tabs", "Tabs"),
                            ("tab_panel", "Tab Panel"),
                            ("accordion", "Accordion"),
                            ("accordion_panel", "Accordion Panel"),
                            ("divider", "Divider"),
                            ("spacer", "Spacer"),
                            ("text", "Text"),
                            ("textarea", "Textarea"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("datetime", "DateTime"),
                            ("time", "Time"),
                            ("select", "Select"),
                            ("multiselect", "Multi Select"),
                            ("checkbox", "Checkbox"),
                            ("checkbox_group", "Checkbox Group"),
                            ("radio", "Radio"),
                            ("switch", "Switch"),
                            ("slider", "Slider"),
                            ("file", "File Upload"),
                            ("image", "Image Upload"),
                            ("lookup", "Lookup"),
                            ("computed", "Computed"),
                            ("rich_text", "Rich Text Editor"),
                            ("code", "Code Editor"),
                            ("color", "Color Picker"),
                            ("rating", "Rating"),
                            ("signature", "Signature"),
                        ],
                        max_length=50,
                    ),
                ),
                ("field_key", models.CharField(blank=True, default="", max_length=255)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="core.form",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="core.formcomponent",
                    ),
                ),
            ],
            options={
                "db_table": "form_components",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.DeleteModel(
            name="FormField",
        ),
    ]
