# Generated by Django 5.1.6 on 2025-12-17 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_formcomponent_delete_formfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("end", "End"),
                            ("approval", "Approval"),
                            ("condition", "Condition"),
                            ("notification", "Notification"),
                            ("timer", "Timer"),
                            ("child_form_entry", "Child Form Entry"),
                            ("view_permission", "View Permission"),
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                            ("fork", "Fork"),
                            ("join", "Join"),
                        ],
                        max_length=50,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "linked_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nodes",
                        to="core.workflowstate",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="core.workflow",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_nodes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_output", models.CharField(default="output", max_length=100)),
                ("target_input", models.CharField(default="input", max_length=100)),
                ("label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "condition_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="core.workflow",
                    ),
                ),
                (
                    "source_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_connections",
                        to="core.workflownode",
                    ),
                ),
                (
                    "target_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_connections",
                        to="core.workflownode",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_connections",
                "ordering": ["created_at"],
            },
        ),
    ]
