# Generated by Django 5.1.6 on 2025-12-19 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_workflownode_workflowconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formcomponent",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("row", "Row"),
                    ("column", "Column"),
                    ("container", "Container"),
                    ("section", "Section"),
                    ("card", "Card"),
                    ("tabs", "Tabs"),
                    ("tab_panel", "Tab Panel"),
                    ("accordion", "Accordion"),
                    ("accordion_panel", "Accordion Panel"),
                    ("divider", "Divider"),
                    ("spacer", "Spacer"),
                    ("repeatable_section", "Repeatable Section"),
                    ("text", "Text"),
                    ("textarea", "Textarea"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("datetime", "DateTime"),
                    ("time", "Time"),
                    ("select", "Select"),
                    ("multiselect", "Multi Select"),
                    ("checkbox", "Checkbox"),
                    ("checkbox_group", "Checkbox Group"),
                    ("radio", "Radio"),
                    ("switch", "Switch"),
                    ("slider", "Slider"),
                    ("file", "File Upload"),
                    ("image", "Image Upload"),
                    ("lookup", "Lookup"),
                    ("computed", "Computed"),
                    ("rich_text", "Rich Text Editor"),
                    ("code", "Code Editor"),
                    ("color", "Color Picker"),
                    ("rating", "Rating"),
                    ("signature", "Signature"),
                ],
                max_length=50,
            ),
        ),
    ]
