# Generated by Django 5.1.6 on 2025-12-24 05:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0004_alter_formcomponent_component_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowconnection",
            name="action_config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="workflownode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("start", "Start"),
                    ("state", "State"),
                    ("end", "End"),
                    ("approval", "Approval"),
                    ("condition", "Condition"),
                    ("notification", "Notification"),
                    ("timer", "Timer"),
                    ("child_form_entry", "Child Form Entry"),
                    ("view_permission", "View Permission"),
                    ("email", "Email"),
                    ("webhook", "Webhook"),
                    ("fork", "Fork"),
                    ("join", "Join"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("available_actions", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_taken",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to_roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_approval_tasks",
                        to="auth.group",
                    ),
                ),
                (
                    "assigned_to_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_approval_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_tasks",
                        to="core.document",
                    ),
                ),
                (
                    "workflow_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_tasks",
                        to="core.workflownode",
                    ),
                ),
            ],
            options={
                "db_table": "approval_tasks",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "status", "-created_at"],
                        name="approval_ta_documen_79e95e_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="approval_ta_status_e4cf41_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentStateHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_state",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("to_state", models.CharField(max_length=255)),
                (
                    "action_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "action_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_history",
                        to="core.document",
                    ),
                ),
                (
                    "transitioned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="state_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="state_transitions",
                        to="core.workflownode",
                    ),
                ),
            ],
            options={
                "db_table": "document_state_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["document", "-created_at"],
                        name="document_st_documen_912c9d_idx",
                    ),
                    models.Index(
                        fields=["transitioned_by", "-created_at"],
                        name="document_st_transit_fa8a53_idx",
                    ),
                ],
            },
        ),
    ]
